seed: 42 # seed
saved_dir: ./saved # save directory
exp_name: 1_Test # experiment name /saved/exp_name/ 폴더에 모델과 best_log, yaml 파일이 저장됨

model: 
  name: EfficientNet_b7 # 모델 이름 /main/model.py 참고
  class: 18

# cutmix probability
cutmix_prob: 0.5

# data
train_path: ./input/train/images # train에 사용할 Data 경로
valid_path: ./input/valid/images # valid에 사용할 Data 경로
test_path: ./input/eval/images # validation에 사용할 Data 경로

# dataloader
train_dataloader:
  params:
    batch_size: 32
    shuffle: true
    num_workers: 8

valid_dataloader:
  params:
    batch_size: 32
    shuffle: false
    num_workers: 8

# # 사용할 transforms 이름 (현재 사용 x)
# transforms:
#   train: x3d_train # /data_set/data_augmentation.py의 transform_entrypoints 참고
#   valid: x3d_valid # /data_set/data_augmentation.py의 transform_entrypoints 참고

# train setting
epochs: 30 # train epochs

criterion: # loss function
  name: cross_entropy # /model/loss.py의 criterion_entrypoints 참고

optimizer: # optimizer 
  name: Adam # torch.optim의 optimizer 사용 가능
  params:
    lr: 0.001 # 1e3
    weight_decay: 0.00001 # 1e5

scheduler: # lr scheduler
  name: MultiStepLR # torch.optim.lr_scheduler scheduler 사용 가능
  params:
    milestones: [8250, 13750]
    gamma: 0.1